
###  ar_drive.yaml 
### This file defines the configuration for the AR drive system, including port information, drive IDs, and joint specifications.
### It is used to set up the hardware interface for the AR robot arm.
### Set up the port information, drive IDs, and joint specifications for the AR robot arm.
### 0 > simulation (run as a dummy joint), 1 > SOEM (EtherCAT)

port_info:
  port_name: enp3s0

use_torque_offset: false

port_ids: 
  drive_1: 1   # SOEM-connected
  drive_2: 1   # SOEM-connected
  drive_3: 1   # SOEM-connected
  drive_4: 1   # SOEM-connected
  drive_5: 0   # dummy (disconnected/unplugged)
  drive_6: 1   # SOEM-connected


drives:
  drive_1:
    joints:
      Arm_joint1:
        gear_ratio: 16
        encoder_res: 256
        encoder_offset: 4000
        # torque_gamma:
        log_joint: false
  drive_2:
    joints:
      Arm_joint2:
        gear_ratio: 16
        encoder_res: 256
        encoder_offset: 4000
        # torque_gamma:
        log_joint: false
  drive_3:
    joints:
      Arm_joint3:
        gear_ratio: 16
        encoder_res: 256
        encoder_offset: 4000
        # torque_gamma:
        log_joint: false
  drive_4:
    joints:
      Arm_joint4:
        gear_ratio: 16
        encoder_res: 256
        encoder_offset: 4000
        # torque_gamma:
        log_joint: false
  drive_5:
    joints:
      Arm_joint5:
        gear_ratio: 16
        encoder_res: 256
        encoder_offset: 4000
        # torque_gamma:
        log_joint: false
  drive_6:
    joints:
      Arm_joint6:
        gear_ratio: 16
        encoder_res: 256
        encoder_offset: 4000
        # torque_gamma:
        log_joint: false
    