#Imaging Action definition
uint8 action
string planning_group
trajectory_msgs/JointTrajectory trajectory

# For ui command on off servo
string[] joint_names

int32 drive_id
int32 slave_id
---
#result definition
int32 status
---
